function Jac_tot = youBot_jacobian_XZRy(th2,th3,th4)
%YOUBOT_JACOBIAN_XZRY
%    JAC_TOT = YOUBOT_JACOBIAN_XZRY(TH2,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Dec-2019 16:34:04

t2 = pi.*(5.0./3.6e1);
t3 = t2+th2;
t4 = sin(t3);
t5 = pi.*(1.4e1./4.5e1);
t6 = t5+th3;
t7 = cos(t3);
t8 = cos(t6);
t9 = pi.*(3.1e1./7.2e1);
t10 = t9+th4;
t11 = sin(t6);
t12 = cos(t10);     
t13 = t4.*t11;
t21 = t7.*t8;
t14 = t12.*(t13-t21).*(2.3e1./1.25e2);
t15 = t7.*t8.*(2.7e1./2.0e2);
t16 = sin(t10);
t17 = t7.*t11;
t18 = t4.*t8;
t19 = t17+t18;
t20 = t16.*t19.*(2.3e1./1.25e2);
t22 = th2+th3-pi.*(1.0./2.0e1);
t23 = cos(t22);
t26 = pi.*(4.3e1./3.6e2);
t24 = -t26+th2+th3+th4;
t25 = sin(t24);
Jac_tot = reshape([t4.*(3.1e1./2.0e2)+t14+t15+t20-t4.*t11.*(2.7e1./2.0e2),t7.*(3.1e1./2.0e2)-t23.*(2.7e1./2.0e2)-t25.*(2.3e1./1.25e2),-1.0,t14+t15+t20-t4.*t11.*(2.7e1./2.0e2),t23.*(-2.7e1./2.0e2)-t25.*(2.3e1./1.25e2),-1.0,t14+t20,t25.*(-2.3e1./1.25e2),-1.0],[3,3]);
