function C = C_3DOF(dq1,dq2,dq3,q2,q3)
%C_3DOF
%    C = C_3DOF(DQ1,DQ2,DQ3,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Dec-2020 14:44:56

t2 = q2+q3;
t3 = sin(t2);
t4 = t3.*1.407741e-2;
t5 = sin(q2);
t6 = t5.*3.718295e-2;
t7 = t4+t6;
t8 = sin(q3);
t9 = t3.*(3.1e1./2.0e2);
t10 = t8.*(2.7e1./2.0e2);
t11 = t9+t10;
t12 = dq1+dq2+dq3;
C = reshape([-dq2.*t7-dq3.*t11.*9.0822e-2,dq1.*t7-dq3.*t8.*1.226097e-2,dq2.*t8.*1.226097e-2+dq1.*t11.*9.0822e-2,-dq1.*t7-dq2.*t7-dq3.*(t4+t8.*1.226097e-2),dq3.*t8.*(-1.226097e-2),t8.*(dq1+dq2).*1.226097e-2,t11.*t12.*(-9.0822e-2),t8.*t12.*(-1.226097e-2),0.0],[3,3]);
