function dJ0E_3DOF = dJ0E_3DOF(q1,q2,q3)
%DJ0E_3DOF
%    DJ0E_3DOF = DJ0E_3DOF

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Dec-2020 14:44:57

dJ0E_3DOF = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
