function G = G_3DOF(q1,q2,q3)
%G_3DOF
%    G = G_3DOF(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Dec-2020 14:44:56

t2 = q1+q2+q3;
t3 = cos(t2);
t4 = q1+q2;
t5 = cos(t4);
G = [t3.*(-8.9096382e-1)-t5.*2.3533209-cos(q1).*3.9515661;t3.*(-8.9096382e-1)-t5.*2.3533209;t3.*(-8.9096382e-1)];
