function out1 = iJ0E_3DOF(q1,q2,q3)
%IJ0E_3DOF
%    OUT1 = IJ0E_3DOF(Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Dec-2020 14:44:57

t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = sin(q1);
t6 = t3.*t5;
t7 = cos(q1);
t10 = t4.*t7;
t8 = t6-t10;
t9 = 1.0./t8;
out1 = reshape([t3.*t9.*(-6.451612903225806),t9.*(t3.*2.7e1+t7.*3.1e1).*2.389486260454002e-1,t7.*t9.*(-7.407407407407407),t4.*t9.*(-2.0e2./3.1e1),t9.*(t4.*2.7e1+t5.*3.1e1).*(2.0e2./8.37e2),t5.*t9.*(-2.0e2./2.7e1),0.0,0.0,-1.0],[3,3]);
