function J0E_3DOF = J0E_3DOF(q1,q2,q3)
%J0E_3DOF
%    J0E_3DOF = J0E_3DOF(Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Dec-2020 14:44:57

t2 = q1+q2;
t3 = sin(t2);
t4 = cos(t2);
t5 = t4.*(2.7e1./2.0e2);
J0E_3DOF = reshape([t3.*(-1.35e-1)-sin(q1).*1.55e-1,t5+cos(q1).*(3.1e1./2.0e2),-1.0,t3.*(-1.35e-1),t5,-1.0,0.0,0.0,-1.0],[3,3]);
