function A = M_3DOF(q2,q3)
%M_3DOF
%    A = M_3DOF(Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    08-Dec-2020 14:44:56

t2 = q2+q3;
t3 = cos(t2);
t4 = cos(q2);
t5 = cos(q3);
t6 = t5.*2.452194e-2;
t7 = t3.*1.407741e-2;
t8 = t4.*3.718295e-2;
t9 = t6+t7+t8+1.29924e-1;
t10 = t5.*1.226097e-2;
t11 = t7+t10+1.7544e-2;
t12 = t10+1.7544e-2;
A = reshape([t3.*2.815482e-2+t4.*7.43659e-2+t6+4.47134e-1,t9,t11,t9,t6+1.29924e-1,t12,t11,t12,1.7544e-2],[3,3]);
