function Jac_tot_inv = Jacobian_tot_youbot_vf_inverse_3joints(th2,th3,th4)
%JACOBIAN_TOT_YOUBOT_VF_INVERSE_3JOINTS
%    JAC_TOT_INV = JACOBIAN_TOT_YOUBOT_VF_INVERSE_3JOINTS(TH2,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    06-Dec-2019 15:24:57

t2 = pi.*(9.0./2.0e1);
t3 = t2+th2+th3;
t4 = pi.*(1.4e1./4.5e1);
t5 = t4+th3;
t6 = cos(t5);
t7 = 1.0./t6;
t8 = sin(t3);
t9 = cos(t3);
t10 = pi.*(5.0./3.6e1);
t11 = t10+th2;
t12 = pi.*(3.1e1./7.2e1);
t13 = t12+th4;
t14 = sin(t13);
t15 = cos(t11);
t16 = sin(t11);
t17 = pi.*(2.9e1./1.2e2);
t18 = t17+th3+th4;
t19 = sin(t18);
Jac_tot_inv = reshape([t7.*t8.*(2.0e2./3.1e1),t7.*(t8.*2.7e1-t15.*3.1e1).*(-2.0e2./8.37e2),t7.*t15.*(-2.0e2./2.7e1),t7.*t9.*(2.0e2./3.1e1),t7.*(t9.*2.7e1+t16.*3.1e1).*(-2.0e2./8.37e2),t7.*t16.*(2.0e2./2.7e1),t7.*t14.*(1.84e2./1.55e2),t7.*(t14.*2.7e1-t19.*3.1e1).*(-4.396654719235364e-2),t7.*(t6.*1.35e2+t19.*1.84e2).*(-1.0./1.35e2)],[3,3]);
