function Jac_tot_t = Jacobian_tot_youbot_vf_transpose_3joints(th2,th3,th4)
%JACOBIAN_TOT_YOUBOT_VF_TRANSPOSE_3JOINTS
%    JAC_TOT_T = JACOBIAN_TOT_YOUBOT_VF_TRANSPOSE_3JOINTS(TH2,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Mar-2020 16:16:23

t2 = pi.*(9.0./2.0e1);
t3 = t2+th2+th3;
t7 = pi.*(4.3e1./3.6e2);
t4 = -t7+th2+th3+th4;
t5 = pi.*(5.0./3.6e1);
t6 = t5+th2;
t8 = sin(t4);
t9 = cos(t6);
t10 = cos(t3);
t11 = t10.*(2.7e1./2.0e2);
t12 = cos(t4);
t13 = t12.*1.886e-1;
t14 = sin(t3);
t15 = th2+th3-pi.*(1.0./2.0e1);
t16 = cos(t15);
Jac_tot_t = reshape([t11+t13+sin(t6).*(3.1e1./2.0e2),t11+t13,t13,t8.*(-1.154841931595954e-17)+t9.*9.491012693391987e-18-t14.*8.266365894244634e-18,t8.*(-1.154841931595954e-17)-t14.*8.266365894244634e-18,t8.*(-1.154841931595954e-17),t8.*(-1.886e-1)+t9.*(3.1e1./2.0e2)-t16.*(2.7e1./2.0e2),t8.*(-1.886e-1)-t16.*(2.7e1./2.0e2),t8.*(-1.886e-1),0.0,0.0,0.0,-1.0,-1.0,-1.0,6.123233995736766e-17,6.123233995736766e-17,6.123233995736766e-17],[3,6]);
