function Jac_task_inv = Jacobian_task_youbot_vf_inverse_3joints(th2,th3,th4)
%JACOBIAN_TASK_YOUBOT_VF_INVERSE_3JOINTS
%    JAC_TASK_INV = JACOBIAN_TASK_YOUBOT_VF_INVERSE_3JOINTS(TH2,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Mar-2020 16:16:41

t2 = pi.*(9.0./2.0e1);
t3 = t2+th2+th3;
t4 = pi.*(1.4e1./4.5e1);
t5 = t4+th3;
t6 = cos(t5);
t7 = 1.0./t6;
t8 = pi.*(1.37e2./3.6e2);
t9 = t8+th2+th3+th4;
t10 = cos(t9);
t11 = pi.*(5.0./3.6e1);
t12 = t11+th2;
t13 = sin(t3);
t14 = cos(t12);
t15 = sin(t5);
t16 = pi.*(3.1e1./7.2e1);
t17 = t16+th4;
t18 = sin(t12);
t19 = sin(t17);
t20 = cos(t17);
t21 = cos(t3);
t22 = t14.^2;
Jac_task_inv = reshape([t7.*t13.*(2.0e2./3.1e1),t7.*(t13.*5.4e1-t14.*6.2e1).*(-1.0e2./8.37e2),t7.*t14.*(-2.0e2./2.7e1),t7.*t21.*(2.0e2./3.1e1),t7.*(t18.*6.2e1+t21.*5.4e1).*(-1.0e2./8.37e2),t7.*t18.*(2.0e2./2.7e1),t7.*(t6.*t10.*t14-t10.*t15.*t18-t6.*t13.*t14.*t20+t6.*t13.*t18.*t19+t13.*t14.*t15.*t19+t13.*t15.*t18.*t20).*(9.43e2./7.75e2),t7.*(t10.*t18.*3.1e1+t6.*t10.*t14.*2.7e1-t10.*t15.*t18.*2.7e1+t6.*t20.*t22.*3.1e1-t15.*t19.*t22.*3.1e1-t6.*t13.*t14.*t20.*2.7e1+t6.*t13.*t18.*t19.*2.7e1-t6.*t14.*t18.*t19.*3.1e1+t13.*t14.*t15.*t19.*2.7e1+t13.*t15.*t18.*t20.*2.7e1-t14.*t15.*t18.*t20.*3.1e1).*(-4.506571087216249e-2),t7.*(t6.*1.35e3+sin(th3+th4+pi.*(2.9e1./1.2e2)).*1.886e3).*(-7.407407407407407e-4)],[3,3]);
