function T01 = MGD_T01(th1)
%MGD_T01
%    T01 = MGD_T01(TH1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Feb-2020 17:10:16

t3 = pi.*(1.69e2./1.8e2);
t2 = -t3+th1;
t4 = sin(t2);
t5 = cos(t2);
T01 = reshape([t5,-t4,0.0,0.0,t4,t5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.47e2./1.0e3,1.0],[4,4]);
