session_manager:
  sessions:
    - session_1:
        initial_config:
          target_height: 1.75 #0.8 
          restitution: 0.6
          gravity: 9.807
    - session_2:
        initial_config:
          target_height: 1.75 #0.8
          restitution: 0.6
          gravity: 9.807
    - session_3:
        initial_config:
          target_height: 1.75 #0.9
          restitution: 0.6
          gravity: 9.807
    - session_4:
        initial_config:
          target_height: 1.75 #0.9
          restitution: 0.6
          gravity: 9.807
    - session_5:
        initial_config:
          target_height: 1.75 #0.7
          restitution: 0.6
          gravity: 9.807
    - session_5:
        initial_config:
          target_height: 1.75 #0.7
          restitution: 0.6
          gravity: 9.807
