
/*
function Jac_tot_t = Jacobian_tot_youbot_transpose_vf(th1;
th2;
th3;
th4)
%JACOBIAN_TOT_YOUBOT_TRANSPOSE_VF
%    JAC_TOT_T = JACOBIAN_TOT_YOUBOT_TRANSPOSE_VF(TH1;
TH2;
TH3;
TH4)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26 - Jun - 2019 09:49:27

Manual optimization achieved by Vincent FORTINEAU, Ph.D Student at L2S
under the supervision of Pedro RODRIGUEZ AYERBE and Maria MAKAROV

*/

#include "youbot_ros_control/jacobian.h"


void youBotJacobianT(const float thetas[5], float jac_matrix[][6]) 
{
	float t2 = thetas[0];
	float t3 = thetas[1];
	float t4 = thetas[2];
	float t5 = thetas[3];
	float t8 = t2 + t3;
	float t7 = t8 + t4;
	float t6 = t7 + t5;
	float t9 = t6 - 2*t2;
	float t10 = -t2 + t3 + t4;
	float t11 = t2 - t3;
	float t12 = 0.0330;
	float t13 = 1.570796326794896;
	float t14 = -t2 + t13;
	float t15 = cos(t6);
	float t16 = t15*6.15e-2;
	float t17 = cos(t7);
	float t18 = t17*6.75e-2;
	float t19 = cos(t8);
	float t20 = t19*7.75e-2;
	float t21 = cos(t9);
	float t22 = cos(t10);
	float t23 = cos(t11);
	float t24 = sin(t6);
	float t24b = t24*(-6.15e-2);
	float t25 = sin(t7)*6.75e-2;
	float t26 = sin(t8)*7.75e-2;
	float t27 = sin(t9);
	float t28 = sin(t10);
	float t29 = sin(t11);
	float t30 = t29*7.75e-2;
	float t31 = t21*6.15e-2;
	float t32 = t22*6.75e-2;
	float t33 = t27*6.15e-2;
	float t34 = t28*6.75e-2;
	float t35 = t3 + t4 + t5;
	float t36 = sin(t35)*(-0.1230);
	float t37 = t3 + t4;
	float t38 = sin(t37)*0.1350;
	float t39 = sin(t2);
	float t40 = cos(t2);
	float t41 = t16 + t18;
	float t42 = t24b - t25;

	float j00 = t41 + t20 - t21*6.15e-2 - t22*6.75e-2 - t23*7.75e-2 - t12*cos(t14);
	float j10 = t41 + t20 + t23*7.75e-2 + t31 + t32;
	float j20 = t41 + t31 + t32;
	float j30 = t16 + t31;
	float j40 = 0.0;
	
	float j01 = t42 - t26 - t27*6.15e-2 - t28*6.75e-2 + t30 - t12*sin(t14);
	float j11 = t42 - t26 - t30 + t33 + t34;
	float j21 = t42 + t33 + t34;
	float j31 = t24b + t33;
	float j41 = 0.0;
	
	float j02 = 0.0;
	float j12 = t36 - t38 - sin(t3)*0.1550;
	float j22 = t36 - t38;
	float j32 = t36;
	float j42 = 0.0;
	
	float j03 = 0.0;
	float j13 = -t39;
	float j23 = -t39;
	float j33 = -t39;
	float j43 = (t24 + t27)*5.0e-1;
	
	float j04 = 0.0;	
	float j14 = -t40;
	float j24 = -t40;
	float j34 = -t40;
	float j44 = (t15 - t21)*5.0e-1;
	
	float j05 = 1.0;
	float j15 = 0;
	float j25 = 0;
	float j35 = 0;
	float j45 = cos(t35);
	
	jac_matrix[0][0] = j00;
	jac_matrix[0][1] = j01;
	jac_matrix[0][2] = j02;
	jac_matrix[0][3] = j03;
	jac_matrix[0][4] = j04;
	jac_matrix[0][5] = j05;

	jac_matrix[1][0] = j10;
	jac_matrix[1][1] = j11;
	jac_matrix[1][2] = j12;
	jac_matrix[1][3] = j13;
	jac_matrix[1][4] = j14;
	jac_matrix[1][5] = j15;

	jac_matrix[2][0] = j20;
	jac_matrix[2][1] = j21;
	jac_matrix[2][2] = j22;
	jac_matrix[2][3] = j23;
	jac_matrix[2][4] = j24;
	jac_matrix[2][5] = j25;

	jac_matrix[3][0] = j30;
	jac_matrix[3][1] = j31;
	jac_matrix[3][2] = j32;
	jac_matrix[3][3] = j33;
	jac_matrix[3][4] = j34;
	jac_matrix[3][5] = j35;

	jac_matrix[4][0] = j40;
	jac_matrix[4][1] = j41;
	jac_matrix[4][2] = j42;
	jac_matrix[4][3] = j43;
	jac_matrix[4][4] = j44;
	jac_matrix[4][5] = j45;	
}

// Jacobian computed with only joint 4 as variable (the other joints are set to specific positions)

void youBotJacobianTJoint4(const float th4, float jac_matrix[][6]) 
{
    float t2 = M_PI*(3.1e1/7.2e1);
    float t3 = t2 + th4;
    float t4 = 1.23e2/1.0e3;

    jac_matrix[0][0] = cos(t3)*(-t4);
    jac_matrix[0][1] = 0;
    jac_matrix[0][2] = sin(t3)*(t4);
    jac_matrix[0][3] = 0;
    jac_matrix[0][4] = 0; //-1;
    jac_matrix[0][5] = 0.0;
}

void youBotJacobianTJoint3(const float th3, float jac_matrix[][6]) 
{
    float t2 = M_PI*(1.4e1/4.5e1);;
    float t3 = t2 + th3;
    float t4 = cos(t3);
    float t5 = sin(t3);
 
    jac_matrix[0][0] = t4*(0.123) - t5*(2.7e1/2.0e2);
    jac_matrix[0][1] = 0;
    jac_matrix[0][2] = t4*(-2.7e1/2.0e2) - t5*(0.123);
    jac_matrix[0][3] = 0;
    jac_matrix[0][4] = 0; //-1;
    jac_matrix[0][5] = 0.0;
}

void youBotJacobianTJoints34(const float thetas[5], float jac_matrix[][6]) 
{
    float th3 = thetas[2];
    float th4 = thetas[3];
    
    float t2 = M_PI*(2.9e1/1.2e2);
    float t3 = t2 + th3 + th4;
    float t4 = M_PI*(1.4e1/4.5e1);
    float t5 = t4 + th3;
    float t6 = sin(t3);
    float t7 = cos(t5);
    float t8 = cos(t3);
    float t9 = t8*(1.23e2/1.0e3);

    jac_matrix[0][0] = t9 - sin(t5)*(2.7e1/2.0e2);;
    jac_matrix[0][1] = 0;
    jac_matrix[0][2] = t6*(-0.123) - t7*(2.7e1/2.0e2);
    jac_matrix[0][3] = 0.0;
    jac_matrix[0][4] = -1.0;
    jac_matrix[0][5] = 0;
    
    jac_matrix[1][0] = t9;
    jac_matrix[1][1] = 0;
    jac_matrix[1][2] = t6*(-0.123);   
    jac_matrix[1][3] = 0.0;    
    jac_matrix[1][4] = -1.0;    
    jac_matrix[1][5] = 0;
}


void youBotJacobianTJoints234(const float thetas[5], float jac_matrix[][6]) 
{
    float th2 = thetas[1];
    float th3 = thetas[2];
    float th4 = thetas[3];
    
    float t2 = M_PI*(0.45); 
    float t3 = t2 + th2 + th3; 
    float t7 = M_PI*(4.3e1/3.6e2); 
    float t4 = -t7 + th2 + th3 + th4; 
    float t5 = M_PI*(5.0/3.6e1); 
    float t6 = t5 + th2; 
    float t8 = sin(t4)*(-0.123); 
    float t9 = cos(t6); 
    float t10 = cos(t3); 
    float t11 = t10*(0.135); 
    float t12 = cos(t4);
    float t13 = t12*(0.123); 
    float t15 = th2 + th3 - M_PI*(0.05);
    float t16 = cos(t15)*(0.135);

    jac_matrix[0][0] = t11 + t13 + sin(t6)*(0.155);
    jac_matrix[0][1] = 0;
    jac_matrix[0][2] = t8* + t9*(0.155) - t16;
    jac_matrix[0][3] = 0.0;
    jac_matrix[0][4] = -1.0;
    jac_matrix[0][5] = 0;
    
    jac_matrix[1][0] = t11 + t13;
    jac_matrix[1][1] = 0;
    jac_matrix[1][2] = t8 - t16;    
    jac_matrix[1][3] = 0.0;    
    jac_matrix[1][4] = -1.0;    
    jac_matrix[1][5] = 0;

    jac_matrix[2][0] = t13;
    jac_matrix[2][1] = 0;
    jac_matrix[2][2] = t8;
    jac_matrix[2][3] = 0.0;
    jac_matrix[2][4] = -1.0;
    jac_matrix[2][5] = 0;
}
