#!/usr/bin/env python

import time
import rospy
import tf 
import numpy as np
from copy import deepcopy
from geometry_msgs.msg import WrenchStamped, Twist

g = 9.80665

sensor_data = WrenchStamped()
BIAS = [-14.3223, 1.2478, -6.2585, 0.0271, 0.7662, 0.0359]
GRAVITY = np.array([0., 0., 0.])
LEVER = np.array([0., 0., 0.])
AVG_VAL = 10 # will average the Bias estimation to avoid noise from z mainly

# For rotation matrix, the inverse is the transpose matrix
def weight_projection(matrix, z):
    return [-matrix[0][2]*z, -matrix[1][2]*z, -matrix[2][2]*z]

def getForceCallback(data):
    global sensor_data
    sensor_data = data
    

if __name__=="__main__":

    rospy.init_node('force_sensor_utils')
    
    listener = tf.TransformListener()
    
    rate = rospy.Rate(500.0)
    
    sensor_frame = "sensor"
    parent_frame = "arm_link_0"
    
    m = rospy.get_param('~sensor_mass', 0.1096) #mass in kg
    l = rospy.get_param('~sensor_arm_leevr', 0.0103) # in m
    not_initialized_bias = rospy.get_param('~bias', True) 
    
    z = g*m
                          
    sub_force = rospy.Subscriber("netft_data", WrenchStamped,
                                 getForceCallback)
    pub_force_cor = rospy.Publisher('force_sensor/grav_comp',
                               WrenchStamped, queue_size=1)  
    time.sleep(0.2)

    if(not_initialized_bias):
        BIAS = [0., 0., 0., 0., 0., 0.]
        counter = AVG_VAL 

    while not rospy.is_shutdown():

        try:
            tf_sens = listener.lookupTransform(sensor_frame, parent_frame, rospy.Time(0))
		                                            
        except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException) as err:
            rospy.logwarn_throttle(1.0, err)
            continue
    
        tf_ROS = tf.TransformerROS()
        mat_w_gravity = tf_ROS.fromTranslationRotation(tf_sens[0], tf_sens[1])
        
        GRAVITY = deepcopy(weight_projection(mat_w_gravity, z))
        
        LEVER[0] = GRAVITY[1] * l
        LEVER[1] = GRAVITY[0] * (-l)
        
        grav_comp_data = deepcopy(sensor_data) # deepcopy to avoid undesired thread behaviour
        grav_comp_data.wrench.force.x = grav_comp_data.wrench.force.x - GRAVITY[0] - BIAS[0]
        grav_comp_data.wrench.force.y = grav_comp_data.wrench.force.y - GRAVITY[1] - BIAS[1]
        grav_comp_data.wrench.force.z = grav_comp_data.wrench.force.z - GRAVITY[2] - BIAS[2]
        
        grav_comp_data.wrench.torque.x = grav_comp_data.wrench.torque.x - LEVER[0] - BIAS[3]
        grav_comp_data.wrench.torque.y = grav_comp_data.wrench.torque.y - LEVER[1] - BIAS[4]
        grav_comp_data.wrench.torque.z = grav_comp_data.wrench.torque.z - LEVER[2] - BIAS[5]
        
        if(not_initialized_bias):
            BIAS[0] += grav_comp_data.wrench.force.x
            BIAS[1] += grav_comp_data.wrench.force.y
            BIAS[2] += grav_comp_data.wrench.force.z
            
            BIAS[3] += grav_comp_data.wrench.torque.x
            BIAS[4] += grav_comp_data.wrench.torque.y
            BIAS[5] += grav_comp_data.wrench.torque.z            
            
            #grav_comp_data.wrench.force.x = grav_comp_data.wrench.force.x - BIAS[0]
            #grav_comp_data.wrench.force.y = grav_comp_data.wrench.force.y - BIAS[1]
            #grav_comp_data.wrench.force.z = grav_comp_data.wrench.force.z - BIAS[2]
            
            counter -= 1
            
            if counter == 0:
                not_initialized_bias = False
                for bias in BIAS:
                    bias = bias/AVG_VAL
                
        
        pub_force_cor.publish(grav_comp_data)

        rate.sleep()
        
