#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This forward kinematics model of the youbot (KUKA) was computed by 
# Maria MAKAROV (L2S - CentraleSupélec) using Matlab(R) and converted 
# to python by Vincent FORTINEAU (L2S - CentraleSupélec & Université 
# Paris-Sud) with minor modifications
# This code should not be implemented for time sensitive application,
# the version generated by Matlab should be used (more than 4 times
# quicker)

import numpy as np
PI = np.pi

""" KUKA YouBot's arm Denavit-Hartenberg parameters """
DH_Param = {
    'd': [0, 0.033, 0.155, 0.135, 0],
    'alpha': [0, PI/2, 0, 0, -PI/2],
    'r': [0.147, 0, 0, 0, 0.218],
    'theta': [PI*169.0/180.0, PI*65.0/180.0+PI/2, -PI*146.0/180.0, PI*102.5/180.0-PI/2, PI*167.5/180.0],  #THETA = theta - q
    }        


def mattransfo(alpha, d, theta, r):
    s = np.sin
    c = np.cos
    return np.array([[c(theta)         , -s(theta)        , 0.       ,           d],
                     [c(alpha)*s(theta), c(alpha)*c(theta), -s(alpha), -r*s(alpha)],
                     [s(alpha)*s(theta), s(alpha)*c(theta),  c(alpha),  r*c(alpha)],
                     [0.               , 0.               , 0.       ,          1.]])
                     

def forward_kinematic(q):
    
    if type(q) in [list, tuple, np.ndarray]:
        T = np.identity(4)
        for i, th in enumerate(q):
            Ta = mattransfo(DH_Param['alpha'][i], DH_Param['d'][i], DH_Param['theta'][i] - th, DH_Param['r'][i])
            T = np.matmul(T, Ta)
            
        return T

    else:
        raise Exception('please provide proper argument, q should be an array of the 5 thetas')
        
        
        
if __name__ == "__main__":

    th_KUKA = np.array([0, 0, 0, 0, 0])
    
    forward_kinematic(th_KUKA)
