#!/usr/bin/env python


####################
#    INCLUDE
####################


import rospy
import numpy as np
import time
from timeit import default_timer as timer
from copy import deepcopy, copy

import tf
from sensor_msgs.msg import JointState
from geometry_msgs.msg import PoseStamped, Point, Quaternion, Pose

import forward_kinematic as fk


###################
#    FUNCTIONS
###################


thetas = np.array([0.,0.,0.,0.,0.])
SEQ = 0

def getJointPos(joint):
    global thetas
    positions = joint.position
    #print("th1: %f" %positions[0])
    #print("th2: %f" %positions[1])
    #print("th3: %f" %positions[2])
    #print("th4: %f" %positions[3])
    #print("th5: %f" %positions[4])

    for i, theta in enumerate(thetas):
        thetas[i] = positions[i]

def initPoseStamped(t, q):
    
    global SEQ
    
    posi = Point()
    posi.x = t[0]
    posi.y = t[1]
    posi.z = t[2]
    
    quat = Quaternion() 
    quat.x = q[1]
    quat.y = q[2]
    quat.z = q[3]
    quat.w = q[0]
    
    pose = Pose()
    pose.position = posi
    pose.orientation = quat
    
    ps = PoseStamped()
    ps.header.seq = SEQ
    ps.header.stamp = rospy.Time.now()
    ps.header.frame_id = 'sensor'
    ps.pose = pose
    
    SEQ += 1
    return ps

def normalizeQuaternions(q):
    
    norm = np.sqrt(q[0]**2 + q[1]**2 + q[2]**2 + q[3]**2)
    q0 = q[0] * 1./norm
    q1 = q[1] * 1./norm
    q2 = q[2] * 1./norm
    q3 = q[3] * 1./norm
    return np.array([q0, q1, q2, q3])


######################
#       MAIN          
######################


if __name__=="__main__":
    
    global th
    
    rospy.init_node('kinematic_endpoint')
    
    sub = rospy.Subscriber("joint_states", JointState, getJointPos)
    pub = rospy.Publisher('forward_kinematic/sensor',
                               PoseStamped, queue_size=1)  
    
    time.sleep(0.3) # make sur subscriber is ready
    
    th = -110. * np.pi / 180 # rotation along z axis between sensor axis and robot end effector
    z = 0#z = 0.0175 # translation along z between sensor axis and robot end effector
    sensor_link = np.array([
    [np.cos(th), -np.sin(th), 0, 0], 
    [np.sin(th), np.cos(th) , 0, 0], 
    [0         , 0          , 1, z], 
    [0         , 0          , 0, 1]])   
    
    ratio = rospy.get_param('tf_ratio', 1.) # multiply translation by ratio
    freq = rospy.get_param('rate', 1000.)
    
    ref_frame = "base_link"

    listener = tf.TransformListener()
    br = tf.TransformBroadcaster()
    
    rate = rospy.Rate(freq)
    #"""TIMER INIT"""
    #time_fk = np.empty([1000])
    #time_matmul = np.empty([1000])
    #time_quat = np.empty([1000])
    #time_trans = np.empty([1000])
    #time_transform = np.empty([1000])
    #idx = 0
    while not rospy.is_shutdown():
        #start = timer()
    	# the kinematic model used consider the gripper endpoint
        rot_matrix = fk.forward_kinematic(copy(thetas))
        #time_fk[idx] = timer() - start
        #start = timer()
        rot_matrix_sensor = np.matmul(rot_matrix, sensor_link)
        #time_matmul[idx] = timer() - start
        #print(rot_matrix)
        #start = timer()
        #q = tf.transformations.quaternion_from_matrix(rot_matrix)
        #time_quat[idx] = timer() - start  
        #start = timer()
        t = tf.transformations.translation_from_matrix(rot_matrix) 
        #time_trans[idx] = timer() - start
        q_sens = tf.transformations.quaternion_from_matrix(rot_matrix_sensor)
        #q_sens = normalizeQuaternions(q_sens)
        #q = normalizeQuaternions(q)
        
        #pose = initPoseStamped(t, q_sens)        
        #pub.publish(pose)
        t *=  ratio
        #start = timer()
        #br.sendTransform(np.array([0, 0, 0]), np.array([0, 0, 0, 1]), rospy.Time.now(), "world", ref_frame)
        #br.sendTransform(t, q, rospy.Time.now(), "arm", ref_frame)
        br.sendTransform(t, q_sens, rospy.Time.now(), "sensor", ref_frame)
        #time_transform[idx] = timer() - start
        #idx += 1
        rate.sleep()
            
        #print("time_fk, min %f, max %f, mean %f" % (np.min(time_fk), np.max(time_fk), np.mean(time_fk)))
        #print("time_matmul, min %f, max %f, mean %f" % (np.min(time_matmul), np.max(time_matmul), np.mean(time_matmul))) 
        #print("time_quat, min %f, max %f, mean %f" % (np.min(time_quat), np.max(time_quat), np.mean(time_quat)))
        #print("time_trans, min %f, max %f, mean %f" % (np.min(time_trans), np.max(time_trans), np.mean(time_trans)))
        #print("time_transform, min %f, max %f, mean %f" % (np.min(time_transform), np.max(time_transform), np.mean(time_transform)))
        #idx = 0
        #time_fk = np.empty([1000])
        #time_matmul = np.empty([1000])
        #time_quat = np.empty([1000])
        #time_trans = np.empty([1000])
        #time_transform = np.empty([1000])
            
        
