#!/usr/bin/env python


import rospy
import tf 
import numpy as np
from sensor_msgs.msg import WrenchStamped

def getForceTorqueCallback(data):

    force_x = data.wrench.force.x
    

if __name__=="__main__":

    rospy.init_node('sensor_biais_meas')
    
    listener = tf.TransformListener()
    sub = rospy.Subscriber("netft_data", WrenchStamped, getForceTorqueCallback)
    
    rate = rospy.Rate(500.0) # tf gets published at 500Hz approx
    
    
    
    while not rospy.is_shutdown():
    
    
    
    rate.sleep()
